# Environment configuration
env=qa
qa.url=https://practice.qabrains.com/ecommerce/login
browser=chrome
headless=true
timeout=20
screenshotPath=reports/screenshots
saveScreenshots=true
allureResultsPath=reports/allure-results
videoRecording=true
videoPath=reports/videos
videoFps=8
